# Generated by Django 3.0.7 on 2020-06-19 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleLibroDiario',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False, verbose_name='idDetalle')),
                ('debe', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='debe')),
                ('haber', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='haber')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False, verbose_name='idPeriodo')),
                ('fechaInicio', models.DateField(verbose_name='fechaInicioPeriodo')),
                ('fechaFin', models.DateField(verbose_name='fechaFinPeriodo')),
                ('id_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodoContable.DetalleLibroDiario')),
            ],
        ),
        migrations.CreateModel(
            name='LibroDiario',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False, verbose_name='idLibro')),
                ('num_asiento', models.IntegerField()),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('id_transaccion', models.ManyToManyField(to='transaccion.Transaccion')),
            ],
            options={
                'verbose_name': 'LibroDiario',
            },
        ),
        migrations.AddField(
            model_name='detallelibrodiario',
            name='id_libro',
            field=models.ManyToManyField(to='periodoContable.LibroDiario'),
        ),
    ]
