# Generated by Django 3.0.7 on 2020-06-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TablasAmortizacion',
            fields=[
                ('id_tablas', models.AutoField(primary_key=True, serialize=False, verbose_name='idTablasAmortizacion')),
                ('monto', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='montoTablas')),
                ('tipo_credito', models.CharField(max_length=50, verbose_name='tipoCredito')),
                ('meses_plazo', models.CharField(max_length=50, verbose_name='mesesPlazo')),
                ('tipo_transaccion', models.CharField(max_length=50, verbose_name='tipoTransaccion')),
            ],
            options={
                'verbose_name': 'Tablas',
            },
        ),
    ]
