# Generated by Django 3.0.7 on 2020-07-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('IDCard', models.CharField(max_length=45, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=120, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=120, verbose_name='apellidos')),
                ('address', models.CharField(max_length=500, verbose_name='direccion')),
                ('phone', models.CharField(max_length=45, verbose_name='telefono')),
                ('date', models.DateField(verbose_name='fechaNacimiento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
