# Generated by Django 3.0.7 on 2020-07-05 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.AddField(
            model_name='user',
            name='dateBirth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='fechaNacimiento'),
            preserve_default=False,
        ),
    ]
