# Generated by Django 3.0.7 on 2020-07-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200705_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codeRegister',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
