# Generated by Django 3.0.7 on 2020-07-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('users', '0007_auto_20200706_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='roles.Role'),
        ),
    ]
