# Generated by Django 3.0.7 on 2020-07-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200712_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('is_Socio', 'is Socio'), ('is_Usuario', 'is Usuario')]},
        ),
    ]
