# Generated by Django 3.0.7 on 2020-06-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitud', '0001_initial'),
        ('tablasAmortizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id_credito', models.AutoField(primary_key=True, serialize=False, verbose_name='idCredito')),
                ('id_Solicitud', models.ManyToManyField(to='solicitud.Solicitud')),
                ('id_tablas', models.ManyToManyField(to='tablasAmortizacion.TablasAmortizacion')),
            ],
            options={
                'verbose_name': 'Creditos',
            },
        ),
    ]
