# Generated by Django 3.0.7 on 2020-06-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False, verbose_name='idTransaccion')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='valorTransaccion')),
                ('tipo_transaccion', models.CharField(choices=[('R', 'Retiro'), ('D', 'Deposito')], max_length=1, verbose_name='tipoTransaccion')),
                ('idSolicitud', models.ManyToManyField(to='solicitud.Solicitud')),
            ],
            options={
                'verbose_name': 'transacciones',
            },
        ),
    ]
