# Generated by Django 3.0.7 on 2020-06-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodoContable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCuenta',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False, verbose_name='idPlan')),
                ('nombre_cuenta', models.CharField(max_length=80, verbose_name='nombreCuenta')),
                ('tipo', models.CharField(max_length=50, verbose_name='tipoCuenta')),
                ('categoria', models.CharField(max_length=50, verbose_name='categoriaCuenta')),
                ('nivel', models.CharField(max_length=50, verbose_name='nivelCuenta')),
                ('id_detalleLibro', models.ManyToManyField(to='periodoContable.DetalleLibroDiario')),
            ],
            options={
                'verbose_name': 'PlandeCuentas',
            },
        ),
    ]
